autentica/urls.py
from django.urls import path
from .views import login_user, logout_user


urlpatterns = [
    path('login_user', login_user, name="login_user"),
    path('logout_user', logout_user, name="logout_user")

]

proyecto_base/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('datos_api.urls')),
    path('', include('modelo_datos.urls')),
    path('', include('autentica.urls')),
]

modelo_datos/models.py
from django.db import models

# Create your models here.

#clase para almacenar puntos con longitud y latitud
class Punto(models.Model):
    nombre_punto = models.CharField(max_length=100, null=False, blank=False, verbose_name="Nombre")
    longitud = models.FloatField()
    latitud = models.FloatField()
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    
    class Meta:
        verbose_name = "punto"
        verbose_name_plural = "puntos"
        ordering = ["nombre_punto"]

    def __str__(self):
        return self.nombre_punto

class Propietario(models.Model):
    nombre = models.CharField(max_length=100, null=False, blank=False, verbose_name="Nombre")
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    
    class Meta:
        verbose_name = "propietario"
        verbose_name_plural = "propietarios"

    def __str__(self):
        return self.nombre
    
class Subestacion(models.Model):
    #regiones de chile
    REGIONES = [
    ('3','antofagasta'),
    ('11','araucania'),
    ('1','arica-parinacota'),
    ('4','atacama'),
    ('10','biobio'),
    ('5','coquimbo'),
    ('13','los-lagos'),
    ('12','los-rios'),
    ('9','maule'),
    ('7','metropolitana'),
    ('16','nuble'),
    ('8','ohiggins'),
    ('2','tarapaca'),
    ('6','valparaiso')
    ]

    nombre_subestacion = models.CharField(max_length=100, null=False, blank=False, verbose_name="Nombre")
    url_subestacion = models.URLField(max_length = 200, null=False, blank=False)
    id_subestacion = models.IntegerField(null=False, blank=False)
    id_punto = models.ForeignKey(Punto, related_name="get_sub", on_delete=models.SET_NULL, null=True)
    region = models.CharField(max_length=20,choices=REGIONES,null=True,blank=True,verbose_name="Region")
    propietario = models.ForeignKey(Propietario, on_delete=models.SET_NULL, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")  
    
    class Meta:
        verbose_name = "subestacion"
        verbose_name_plural = "subestaciones"    
    
    def __str__(self):
        return self.nombre_subestacion

class Linea(models.Model):
    TENSIONES = [
        ("44", "44KV"),
        ("66", "66KV"),
        ("110", "110KV"),
        ("154", "154KV"),
        ("220", "220KV"),
        ("345", "345KV"),
        ("500", "500KV")
    ]  
    
    nombre_linea = models.CharField(max_length=100, null=False, blank=False, verbose_name="Nombre")
    largo = models.FloatField(null=False, blank=False)
    tension = models.CharField(max_length=20,choices=TENSIONES,null=True,blank=True,verbose_name="Tension")
    puntos = models.ManyToManyField(Punto, related_name="get_linea")
    propietario = models.ForeignKey(Propietario, on_delete=models.SET_NULL, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    
    class Meta:
        verbose_name = "linea"
        verbose_name_plural = "lineas"    

    def __str__(self):
        return self.nombre_linea

templates/base1.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi Mapa</title>
    <!--Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
        integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js"
        integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD"
        crossorigin="anonymous"></script>
    <!--Mi propio css-->
    <link href="{% static 'map.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/leaflet/dist/leaflet.css" crossorigin="" />
    <script src="https://unpkg.com/leaflet/dist/leaflet.js" crossorigin=""></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">
				<img src="{% static 'logo.jpg' %}" alt="" width="30" height="24" class="d-inline-block align-text-top">
				Mi Mapa
			</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <li class="nav-item">
							<a class="nav-link active" aria-current="page" href="{% url 'lista_se' %}">Subestaciones</a>
						</li>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'lista_lineas' %}">Lineas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'lista_puntos' %}">Puntos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'lista_propietario' %}">Propietarios</a>
                    </li>
					<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Marcador
                        </a>
                        <ul class="dropdown-menu">
							<li>
                                <a class="dropdown-item" href="#">
									<div class="input-group">
										<label for="inp_latitud">Latitud: </label>
                                    </div>
                                    <div class="input-group">
										<input class="form-control" type="text" id="inp_latitud" disabled/>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
									<div class="input-group">
										<label for="inp_latitud">Longitud: </label>
                                    </div>
                                    <div class="input-group">
										<input class="form-control" type="text" id="inp_longitud" disabled/>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item disabled" href="#">Agregar</a>
                            </li>
							<li>
                                <a class="dropdown-item disabled" href="#">Limpiar</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link active" aria-current="page" href="{% url 'logout_user' %}">log out</a>
					{% else %}
						<a class="nav-link active" aria-current="page" href="{% url 'login_user' %}">log in</a>	
					{% endif %}	
                    </li>
                </ul>
            </div>
        </div>
    </nav>
	
		
	{% block contenido1 %}{% endblock contenido1 %}

</body>

</html>

templates/detail_linea.html
{% extends 'base1.html' %}
{% load static %}
{% block contenido1 %}
<div class="container">
    <div class="row justify-content-center">
		<div class="card" >
		  <div class="card-body">
			<h4 class="card-title">{{ linea.nombre_linea }}</h4>
			<p class="card-text">Largo: {{ linea.largo }}</p>
			<p class="card-text">Tension: {{ linea.tension }}</p>
			<p class="card-text">Propietario: {{ linea.propietario }}</p>
			
		  </div>
		</div>
		</br>
		<div>
			<a class="btn btn-primary" href="{% url 'update_lineas' linea.id %}">Actualizar</a> 
			<a class="btn btn-primary" href="{% url 'delete_lineas' linea.id %}">Borrar</a>
		</div>
	</div>
</div>


{% endblock %}

templates/detail_propietario.html
{% extends 'base1.html' %}
{% load static %}
{% block contenido1 %}
<div class="container">
    <div class="row justify-content-center">
		<div class="card" >
		  <div class="card-body">
			<h4 class="card-title">{{ propietario.nombre }}</h4>
			<p class="card-text">Fecha creacion: {{ propietario.fecha_creacion }}</p>
			
		  </div>
		</div>
		</br>
		<div>
			<a class="btn btn-primary" href="{% url 'update_propietarios' propietario.id %}">Actualizar</a> 
			<a class="btn btn-primary" href="{% url 'delete_propietarios' propietario.id %}">Borrar</a>
		</div>
	</div>
</div>


{% endblock %}

templates/detail_punto.html
{% extends 'base1.html' %}
{% load static %}
{% block contenido1 %}
<div class="container">
    <div class="row justify-content-center">
		<div class="card" >
		  <div class="card-body">
			<h4 class="card-title">{{ punto.nombre_punto }}</h4>
			<p class="card-text">Longitud: {{ punto.longitud }}</p>
			<p class="card-text">Latitud: {{ punto.latitud }}</p>
			<p class="card-text">Fecha creacion: {{ punto.fecha_creacion }}</p>
			
		  </div>
		</div>
		</br>
		<div>
			<a class="btn btn-primary" href="{% url 'update_puntos' punto.id %}">Actualizar</a> 
			<a class="btn btn-primary" href="{% url 'delete_puntos' punto.id %}">Borrar</a>
		</div>
	</div>
</div>


{% endblock %}

templates/detail_subestacion.html
{% extends 'base1.html' %}
{% load static %}
{% block contenido1 %}
<div class="container">
    <div class="row justify-content-center">
		<div class="card" >
		  <div class="card-body">
			<h4 class="card-title">{{ subestacion.nombre_subestacion }}</h4>
			<h5 class="card-subtitle mb-2 text-muted">{{ subestacion.get_region_display}}</h5>
			<p class="card-text">ID infotecnica: {{ subestacion.id_subestacion }}</p>
			<p class="card-text">Propietario: {{ subestacion.propietario }}</p>
			<h5 class="card-text">Punto</h5>
			<p class="card-text">Latitud: {{ subestacion.id_punto.latitud }}</p>
			<p class="card-text">Longitud: {{ subestacion.id_punto.longitud }}</p>
		  </div>
		</div>
		</br>
		<div>
			<a class="btn btn-primary" href="{% url 'update_subestacion' subestacion.id %}">Actualizar</a> 
			<a class="btn btn-primary" href="{% url 'delete_subestacion' subestacion.id %}">Borrar</a>
			<a class="btn btn-primary" href="{{ subestacion.url_subestacion }}" target="_blank">Infotecnica</a>
			<a class="btn btn-primary" href="#" onclick="redirecHome('{{ subestacion.id_punto.latitud }}','{{ subestacion.id_punto.longitud }}')">Ir</a>
		</div>
	</div>
</div>
<script>
	let base_url = window.location.origin;
	function redirecHome(lat,lon) {
	  window.open(base_url + "?lat=" + lat + "&" + "lon=" + lon);
	};
</script>

{% endblock %}

templates/form_tipo.html
{% extends 'base1.html' %}
{% block contenido1 %}

<section class="bg-light" id="director">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h1>Crear/Actualizar {{ tipo_objeto }}</h1><br><br>
            </div>
            <div class="col-lg-8">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table-light" >
                        {{ form.as_table }}
                    </table>
                    <br>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block contenido1 %}


    <div class="row mx-2 my-2">
        <div class="col-md-12">
            <div id="map"></div>
			<script>
				let my_icono = "{% static 'se2.png' %}"
            </script>
			<script src="{% static 'mapa.js' %}" defer></script>
        </div>
    </div>
{% endblock contenido1 %}

templates/list_lineas.html
{% extends 'base1.html' %}
{% block contenido1 %}

<section id="home" class="py-5">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Listado de Lineas</h2>
                <br>
				<div>
					<a class="btn btn-primary" href="{% url 'create_lineas' %}">Crear</a> 
                <div>
				<br>
				<table class="table table-bordered border-primary">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre Linea</th>
                        <th scope="col">Tension</th>
                        <th scope="col">Largo</th>
						<th scope="col">Propietario</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for linea in lineas %}
                    <tr>
                        <th scope="row">{{ linea.id }}</th>
                        <td><a href="{% url 'detalle_linea' linea.id %}">{{ linea }}</a></td>
						<td>{{ linea.tension }}</td>
                        <td>{{ linea.largo }}</td>
						<td>{{ linea.propietario }}</td>
                    </tr>
                    {% empty %}
                    <p>No hay lineas disponibles.</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<nav aria-label="Page navigation example">
  <ul class="pagination pagination-mg justify-content-center">
    {% if page_obj.has_previous %}
		<li class="page-item"><a class="page-link" href="?page=1">First</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}
    {% if page_obj.has_next %}
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
    {% endif %}
  </ul>
</nav>


{% endblock %}

templates/list_propietario.html
{% extends 'base1.html' %}
{% block contenido1 %}

<section id="home" class="py-5">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Listado de Propietarios</h2>
                <br>
				<div>
					<a class="btn btn-primary" href="{% url 'create_propietarios' %}">Crear</a> 
                <div>
				<br>
                <table class="table table-bordered border-primary">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre Propietario</th>
						<th scope="col">Fecha creacion</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for propietario in propietarios %}
                    <tr>
                        <th scope="row">{{ propietario.id }}</th>
                        <td><a href="{% url 'detalle_propietario' propietario.id %}">{{ propietario }}</a></td>
						<td>{{ propietario.fecha_creacion }}</td>
                    </tr>
                    {% empty %}
                    <p>No hay Propietarios disponibles.</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<nav aria-label="Page navigation example">
  <ul class="pagination pagination-mg justify-content-center">
    {% if page_obj.has_previous %}
		<li class="page-item"><a class="page-link" href="?page=1">First</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}
    {% if page_obj.has_next %}
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
    {% endif %}
  </ul>
</nav>


{% endblock %}

templates/list_subestaciones.html
{% extends 'base1.html' %}
{% block contenido1 %}

<section id="home" class="py-5">
    <div class="container px-4">
        <div class="row gx-4 justify-content-center">
            <div class="col-lg-8">
                <h2>Listado de Subestaciones</h2>
                <br>
				<div>
					<a class="btn btn-primary" href="{% url 'create_subestacion' %}">Crear</a> 
                <div>
				<br>
                <table class="table table-bordered border-primary">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nombre Subestacion</th>
                        <th scope="col">ID infotecnica</th>
                        <th scope="col">Región</th>
						<th scope="col">Propietario</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for se in subestaciones %}
                    <tr>
                        <th scope="row">{{ se.id }}</th>
                        <td><a href="{% url 'detalle_se' se.id %}">{{ se }}</a></td>
                        <td>{{ se.id_subestacion }}</td>
                        <td>{{ se.region }}</td>
						<td>{{ se.propietario }}</td>
                    </tr>
                    {% empty %}
                    <p>No hay subestaciones disponibles.</p>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>

<nav aria-label="Page navigation example">
  <ul class="pagination pagination-mg justify-content-center">
    {% if page_obj.has_previous %}
		<li class="page-item"><a class="page-link" href="?page=1">First</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}
    {% if page_obj.has_next %}
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
		<li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
    {% endif %}
  </ul>
</nav>


{% endblock %}

templates/login.html
{% extends 'base1.html' %}

{% block contenido1 %}
	<div>
		{% if messages %}
			{% for message in messages %}
				{{message}}
			{% endfor %}
		{% endif %}
	</div>
	<br>
	
 <div class="container my-3">
	 <div class="row">
		 <div class="col-md-4 col-lg-4 py-4">
			 <h2>
				Log in
			</h2>
			<br>
			<form action="" method="post">
				{% csrf_token %}
			  <div class="mb-3">
				<label for="exampleInputEmail1" class="form-label">Usuario</label>
				<input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="username" name="username">
				<div id="username" class="form-text">No debe compartir su usuario</div>
			  </div>
			  <div class="mb-3">
				<label for="contrasena" class="form-label">Contraseña</label>
				<input type="password" class="form-control" id="contrasena" name="password">
			  </div>
			  <button type="submit" class="btn btn-primary">Log In</button>
			</form>
		</div>
	</div>
</div>

{% endblock %}

templates/prueba.html
<!DOCTYPE html>
<html lang="en">

<head>
</head>

<body>
    <h1>Hola esta es una prueba</h1>
</body>

</html>

templates/punto_lista.html
<html>
    <head>
        <title>Mapa</title>
    </head>
    <body>
		<h1>
			Mapa
		</h1>
		<div>
			<ul>
				{% for punto in puntos %}
				<li><a href="{% url 'detalle' punto.pk%}">{{punto.id}}</a></li>
				<li>{{ punto.nombre_punto }}</li>
				<hr/>
				{% empty %}
				<li>No hay objetos</li>
				{% endfor %}
			</ul>
		</div>
		<div class="pagination">
			<span class="step-links">
				{% if page_obj.has_previous %}
					<a href="?page=1">&laquo; first</a>
					<a href="?page={{ page_obj.previous_page_number }}">previous</a>
				{% endif %}

				<span class="current">
					Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
				</span>

				{% if page_obj.has_next %}
					<a href="?page={{ page_obj.next_page_number }}">next</a>
					<a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
				{% endif %}
			</span>
		</div>
    </body>
</html>